### ISSUE TITLE
UI-states bouwen

### ISSUE THREAD

**Issue by christoph3r3w** [christoph3r3w/pleasurable-ui#16]
# Button UI States 

So for the buttons we tried to give the user/reader as much feedback as possible by giving the buttons obvious states and different vibrant colors for each button so they feel more unique and with consistency as well. Each state is thought well of and will surely give the user enough feedback.

<img width="650px" src="https://github.com/christoph3r3w/pleasurable-ui/assets/143999883/f2e5c7b8-d32a-4fa6-b34f-e441fbba93ea">

**Comment by Jason2426** [comment]
✅
