### ISSUE TITLE
Redesign highlight section bouwen

### ISSUE THREAD

**Issue by Jason2426** [christoph3r3w/pleasurable-ui#44]
## [Figma Design for highlightsection on desktop](https://www.figma.com/proto/wOWjvHwU4UoCMEkeNAcjX7/RedPers-Re-design?page-id=1%3A3&node-id=384-180&viewport=-3172%2C338%2C0.44&t=ippCS1oGjCSspONG-1&scaling=scale-down)

![Image](https://github.com/christoph3r3w/pleasurable-ui/assets/144007933/1d53f6e4-209d-41f8-9b15-da4adbfdcb1f)

**Comment by christoph3r3w** [comment]
Voorbeeld : https://x.com/natkohasic/status/1775816021686759707
