### ISSUE TITLE
Article (details) pagina design

### ISSUE THREAD

**Issue by christoph3r3w** [christoph3r3w/pleasurable-ui#5]
## [Article page - mobile](https://www.figma.com/design/wOWjvHwU4UoCMEkeNAcjX7/RedPers-Re-design?node-id=1%3A71&t=M3yi8bB2l85FOEHL-1)

> Read the explanation of the designs here : **[HERE](https://github.com/christoph3r3w/pleasurable-ui/issues/8)**

**Comment by Jason2426** [comment]
Dubbele issue
