### ISSUE TITLE
Desktop design voor home & detailpagina

### ISSUE THREAD

**Issue by christoph3r3w** [christoph3r3w/pleasurable-ui#6]
### **[Desktop design - Home](https://www.figma.com/proto/wOWjvHwU4UoCMEkeNAcjX7/RedPers-Re-design?page-id=1%3A3&node-id=46-269&viewport=-1285%2C-100%2C0.39&t=1DmW9m2UN7r8sqNo-1&scaling=scale-down)**

> For the home page on desktop we wanted a more pleasureable layout for the users, we found alot of inspiration from other news websites across the internet. The highlight section now feels more clear and reduces some scroll time for the user to reach the bottom. The design is pretty basic but we would like to make it better in the upcoming weeks by adding some cool scroll driven animations, this will make the page feel more alive and is one of our endgoals.  

### **[Desktop design - Detailpage](https://www.figma.com/proto/wOWjvHwU4UoCMEkeNAcjX7/RedPers-Re-design?page-id=1%3A70&node-id=109-953&viewport=-1370%2C-447%2C0.31&t=bXBG3BxBboeCrQWH-1&scaling=scale-down)**

> For the detailpage on desktop and mobile we designed a layout that gives the reader a more clear introduction of each article because we felt that was missing for the readers. This page will also be revisited in the next week and we want to make this page more alive by also adding scroll driven animations or other cool interactions. The functions as for now will be placed at this spot but probably be changed in the next week. 

We're happy with both designs and these do also provide a good basis to work on throughout the project because there is alot of room for improvements still.

**Comment by Jason2426** [comment]
The first iteration of the design is done.
