### ISSUE TITLE
Mobile design voor home & detailpage

### ISSUE THREAD

**Issue by christoph3r3w** [christoph3r3w/pleasurable-ui#8]
### **[Mobile design - Home](https://www.figma.com/proto/wOWjvHwU4UoCMEkeNAcjX7/RedPers-Re-design?page-id=0%3A1&node-id=27-899&viewport=-189%2C276%2C0.44&t=uLsKoQr8WfBY0BvK-1&scaling=scale-down)**

> For the homepage design we wanted to solve the problem that the user has to scroll a lot to get to the bottom of the page. In this design we minimized the amount to scroll to the bottom by implementing a pleasurable carousel that we would like to make with CSS. We have thought out many situations but we will look at this again next week cause we're still missing some things. 

### **[Mobile design - Detailpage](https://www.figma.com/proto/wOWjvHwU4UoCMEkeNAcjX7/RedPers-Re-design?page-id=1%3A71&node-id=104-546&viewport=-3%2C-956%2C0.79&t=1IrIvxUzM2jPMfXk-1&scaling=scale-down)**

> For the detailpage design we wanted to give the user/reader a feeling of a newspaper and a clear introduction to each article, which RedPers has implemented but we would like to elevate it. In the next week we will revisit the design for this page and add or change things if we feel its needed.

Both designs feel incomplete yet but we have a good base for now to be worked on throughout this project.

**Comment by Jason2426** [comment]
The design for this week is done.
